### ISSUE TITLE
Switching Boards

### ISSUE THREAD

**Issue by ngorog** [cs361w2019-osu/sprint1-project-group-15#18]
Switch board screens post placement, user board in top right.

**Comment by barnesjt** [comment]
Merged implementation in is18 branch with #22

**Comment by ktran0918** [comment]
This is an accurate implementation of what we discussed. I'd like to propose transition effects to the switch (resizing/moving) if possible. Currently the switch is sudden and may be hard for the user to immediately see a switch has taken place.

Another suggestion of mine is to move the prompt ("place your ships", "select your next attacks") to a better place. Currently the prompts are directly underneath the small board; the user may interpret these to apply to the small board and may perform actions there instead.
