### ISSUE TITLE
Attack Special Cases

### ISSUE THREAD

**Issue by goodletb** [cs361w2019-osu/sprint1-project-group-15#2]
The issue here is to implement a few special cases to do with attacking ships.
- Duplicate attacks ( attacking the same square multiple times should return an INVALID attack.
- Sunk Ship ( detects if all squares of a ship have been hit, and if so the ship is sunk )

**Comment by goodletb** [comment]
Duplicate attacks:
The function for checking duplicate attacks is implemented in the board class as board.isDuplicateAttack(Square location).

**Comment by goodletb** [comment]
Sunk Ship:
The function for checking if a ship has been sunk is implemented in the ship class as ship.isSunk(List<Result> attacksOnBoard).

**Comment by goodletb** [comment]
I managed to get all of the tests passing, however I am running into an issue where I had to add a bunch of extra code to be able to run the tests. The tests pass with the extra code, but once the other code for the attack function and the result class are added the tests should pass with little modification.

**Comment by barnesjt** [comment]
Cool, I took a look at what you got going on and it seems pretty sound. And wow you did a lot of work for a test to get around our currently missing attack implementation, and I see you had to do some stuff in result as well. Looks good Brad, we'll mostly just need some logic put into attack before we can actually test the board from the user end.

**Comment by ngorog** [comment]
Looked at the code, looks well done and runs with my tests.

**Comment by barnesjt** [comment]
Branch was pull requested and merged. Closing issue.
