### ISSUE TITLE
Place Ships with Captain Quarter's

### ISSUE THREAD

**Issue by ngorog** [cs361w2019-osu/sprint1-project-group-15#31]
Ships will have a captain's quarters, with a different amount of hits to sink and location depending on the ship.

Minesweeper: 1 Hit to Sink Captain Quarters
Battleship/Destroyer: 2 Hits to Sink Captain Quarters

**Comment by barnesjt** [comment]
Partially implemented with PR #39. (Captain's Quarter do not yet detect hits differently and ships don't sink when the captain's quarter's is damaged). I believe these are covered under #34. Closing.
