### ISSUE TITLE
Addition of Space Laser Weapon

### ISSUE THREAD

**Issue by barnesjt** [cs361w2019-osu/sprint1-project-group-15#48]
According to Sprint 4 - User Story 4:
"As a user, I want to fire a space laser, to attack the opponent's submarine.
Conversation: The space laser has the advantage over conventional bombs, in that it can penetrate water and ships. Therefore, it can attack a submerged submarine, even one placed under a surface ship. (Conventional bombs can still attack surfaced submarines, however). The option to use space lasers becomes available after player sinks the first opponent's ship."

**Comment by goodletb** [comment]
PR was merged. Closing issue.
