### ISSUE TITLE
Submarine

### ISSUE THREAD

**Issue by ktran0918** [cs361w2019-osu/sprint1-project-group-15#53]
User story 1: As a user, I want to play with a submarine, to add more variety to the game.
- Conversation: A submarine will take up 5 blocks. It can be placed on the surface or submerged.
- Confirmation: Two JUnit tests are written to ensure the "sail" of the submarine is placed correctly. One checks for horizontal placement, the other does vertical. Captain's quarter test now includes testing the submarine as well.

**Comment by barnesjt** [comment]
I'm closing this now as it was implemented with #54 and has it's last fixes pending merge in #57. Additional problems will spawn a new issue should they arise.
